# Generated by Django 3.1.7 on 2021-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quanity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('ON THE WAY', 'ON THE WAY'), ('DELIVERED', 'DELIVERED'), ('CANCEL', 'CANCEL')], default='Pending', max_length=50),
        ),
    ]
